#!/bin/bash

sudo cp set-terminal-theme /usr/local/bin/
sudo cp terminal-theme-monitor /usr/local/bin/
sudo chmod +x /usr/local/bin/set-terminal-theme
sudo chmod +x /usr/local/bin/terminal-theme-monitor

sudo cp terminal-theme-monitor.service /etc/systemd/system/
sudo systemctl daemon-reload
