#!/bin/bash

# add scripts to user path
cp set-kitty-theme "$HOME"/.local/bin/
cp kitty-gnome-theme-monitor "$HOME"/.local/bin/
chmod +x "$HOME"/.local/bin/set-kitty-theme
chmod +x "$HOME"/.local/bin/kitty-gnome-theme-monitor

# add daemon to systemd
systemd_folder="$HOME"/.config/systemd/user
mkdir -p $systemd_folder
echo "[Unit]
Description=Matches Kitty's theme with Gnome light/dark theme

[Service]
Type=forking
ExecStart=$HOME/.local/bin/kitty-gnome-theme-monitor
RemainAfterExit=yes

[Install]
WantedBy=default.target" > $systemd_folder/kitty-gnome-theme-monitor.service

systemctl --user daemon-reload
