#!/bin/bash

# add scripts to user path
cp set-kitty-theme "$HOME"/.local/bin/
cp kitty-gnome-theme-monitor "$HOME"/.local/bin/
chmod +x "$HOME"/.local/bin/set-kitty-theme
chmod +x "$HOME"/.local/bin/kitty-gnome-theme-monitor

# add daemon to systemd
systemd_folder="$HOME"/.config/systemd/user
mkdir -p $systemd_folder
cp kitty-gnome-theme-monitor.service $systemd_folder

systemctl --user daemon-reload
