#!/bin/bash


# kill existing daemon
kitty-gnome-theme-monitor -k
systemctl --user stop kitty-gnome-theme-monitor.service

# remove service
systemd_folder="$HOME"/.config/systemd/user
rm "$systemd_folder"/kitty-gnome-theme-monitor.service 

# remove scripts
rm "$HOME"/.local/bin/set-kitty-theme
rm "$HOME"/.local/bin/kitty-gnome-theme-monitor

# update systemd to remove daemon
systemctl --user daemon-reload
