#!/bin/bash


# kill existing daemon
kitty-gnome-mode-monitor -k
systemctl --user stop kitty-gnome-mode-monitor.service

# remove service
systemd_folder="$HOME"/.config/systemd/user
rm "$systemd_folder"/kitty-gnome-mode-monitor.service

# remove scripts
rm "$HOME"/.local/bin/set-kitty-mode
rm "$HOME"/.local/bin/kitty-gnome-mode-monitor

# update systemd to remove daemon
systemctl --user daemon-reload
